### ISSUE TITLE
Please provide a way to inherit GlyphSet

### ISSUE THREAD

**Issue by joshtriplett** [rust-cli/termtree#30]
If rendering a tree with a non-default GlyphSet, it's inconvenient to add `.with_glyphs(...)` on every node of the tree. It'd be much easier to set it once, at the root, and have it inherited by every node when displaying.

This could be done without breaking backwards compatibility by having a `.with_glyphs_inherit(...)`, or if there isn't a use case for varying node-by-node and backwards compatibility isn't an issue, it could be done by changing `.with_glyphs(...)` to inherit.

**Comment by epage** [comment]
I'm tempted to make a breaking change and to make inheriting the default.

**Comment by joshtriplett** [comment]
That does seem like the far more convenient model, and anyone wanting to use different glyphs at different levels of the tree could always override it.
